services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'

#  stock-service:
#    build:
#      context: ./stock-service
#      dockerfile: Dockerfile
#    container_name: stock-service
#    depends_on:
#      - stock-db
#      - kafka
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD="admin"
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stock-db:5432/stock-db
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#
#    ports:
#      - "8080:8080"

  stock-db:
    image: postgres:latest
    container_name: stock-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock-db
    ports:
      - "5432:5432"


  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    depends_on:
      - product-mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@product-mongodb:27017/product-service?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=product-service
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=password
    ports:
      - "8081:8081"

  product-mongodb:
    image: mongo:latest
    container_name: product-mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db

  order-mysql:
    image: mysql:latest
    container_name: order-mysql
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=order-service
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
    ports:
      - "3360:3306"
    volumes:
        - ./mysql:/var/lib/mysql
        - ./order-service/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - order-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://order-mysql:3306/order-service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8082:8082"