spring:
  application:
    name: test-serv
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


server:
  port: 8083
