version: '3.8'


services:
  stock-api:
    build:
      context: .
    container_name: stock-api
    depends_on:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD="admin"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stock-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock-db
    ports:
      - "5432:5432"